"""Package PlayingCards.io rooms and native TTS scenes from canonical data."""

from __future__ import annotations

import copy
import hashlib
import io
import json
import random
import re
import zipfile
from pathlib import Path
from typing import Any

from card_catalog import (
    GAME_PATH, PCIO_TEMPLATE, ROOT, PLAYER_DECKS, asset_path, atlas_specs,
    load_game, load_pcio_widgets, pcio_card, player_card_types, read_json,
)

TTS_TEMPLATE = ROOT / "source" / "templates" / "tts.json"
LUA_TEMPLATE = ROOT / "source" / "templates" / "tts_bootstrap.lua"
PCIO_CARD_MAX_EDGE = 1024
PCIO_CARD_JPEG_QUALITY = 85


def pcio_card_image_name(source_image: str) -> str:
    # The source extension is part of the key, so foo.png and foo.jpg stay distinct.
    key = hashlib.sha256(source_image.encode("utf-8")).hexdigest()
    return f"pcio_card_{key}.jpg"


def pcio_export_card(card: dict[str, Any]) -> dict[str, str]:
    result = pcio_card(card)
    result["image"] = "package://userassets/" + pcio_card_image_name(card["image"])
    return result


def optimized_card_image(source: Path) -> bytes:
    from PIL import Image, ImageOps

    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original)
        image.thumbnail((PCIO_CARD_MAX_EDGE, PCIO_CARD_MAX_EDGE), Image.Resampling.LANCZOS)
        if "A" in image.getbands() or "transparency" in image.info:
            rgba = image.convert("RGBA")
            image = Image.new("RGB", rgba.size, "white")
            image.paste(rgba, mask=rgba.getchannel("A"))
        else:
            image = image.convert("RGB")
        buffer = io.BytesIO()
        image.save(buffer, "JPEG", quality=PCIO_CARD_JPEG_QUALITY, optimize=True, progressive=True)
        return buffer.getvalue()


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def strings(value: Any):
    if isinstance(value, dict):
        for item in value.values():
            yield from strings(item)
    elif isinstance(value, list):
        for item in value:
            yield from strings(item)
    elif isinstance(value, str):
        yield value


def package_assets(widgets: list[dict[str, Any]]) -> set[str]:
    prefix = "package://userassets/"
    return {value[len(prefix):] for value in strings(widgets) if value.startswith(prefix)}


def build_pcio(output: Path, game_path: Path = GAME_PATH,
               template_path: Path = PCIO_TEMPLATE) -> Path:
    game = load_game(game_path)
    template = read_json(template_path)
    widgets = load_pcio_widgets(game_path, template_path)
    by_id = {card["id"]: card for card in game["cards"]}
    for widget in widgets:
        if widget.get("type") == "cardDeck" and widget["id"] in PLAYER_DECKS.values():
            widget["cardTypes"] = {card_id: pcio_export_card(by_id[card_id]) for card_id in widget["cardTypes"]}
    card_sources = {pcio_card_image_name(card["image"]): asset_path(card["image"], game_path)
                    for card in game["cards"]}
    output.mkdir(parents=True, exist_ok=True)
    # Remove rulebook files generated by older PlayingCards builds.
    (output / "rules.md").unlink(missing_ok=True)
    for previous in output.glob("rules_page_*.jpg"):
        previous.unlink()
    write_json(output / "widgets.json", widgets)
    (output / "schemaVersion").write_text(str(template["schema_version"]), encoding="utf-8")
    members = {
        "widgets.json": (output / "widgets.json").read_bytes(),
        "schemaVersion": (output / "schemaVersion").read_bytes(),
    }
    refs = package_assets(widgets)
    assets_dir = output / "userassets"
    assets_dir.mkdir(exist_ok=True)
    for filename in sorted(refs):
        if filename in card_sources:
            data = optimized_card_image(card_sources[filename])
        else:
            source = asset_path("assets/" + filename, game_path)
            data = source.read_bytes()
        (assets_dir / filename).write_bytes(data)
        members["userassets/" + filename] = data
    # Do not retain heavy originals from an earlier build in the expanded package.
    for previous in assets_dir.iterdir():
        if previous.is_file() and previous.name not in refs:
            previous.unlink()
    archive = output / f"{game['id']}.pcio"
    temporary = archive.with_suffix(".pcio.tmp")
    with zipfile.ZipFile(temporary, "w") as package:
        for name, data in sorted(members.items()):
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            package.writestr(info, data)
    temporary.replace(archive)
    return archive


def remove_guids(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: remove_guids(item) for key, item in value.items() if key != "GUID"}
    if isinstance(value, list):
        return [remove_guids(item) for item in value]
    return value


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def lua_long_string(value: str) -> str:
    separator = "="
    while "]" + separator + "]" in value:
        separator += "="
    return "[" + separator + "[" + value + "]" + separator + "]"


def build_native_save(output: Path, urls: dict[str, str], game_path: Path = GAME_PATH,
                      template_path: Path = TTS_TEMPLATE, lua_path: Path = LUA_TEMPLATE) -> Path:
    game = load_game(game_path)
    types = player_card_types(game)
    specs = atlas_specs(len(types))
    save = read_json(template_path)

    def replace_assets(value: Any) -> Any:
        if isinstance(value, dict):
            return {key: replace_assets(item) for key, item in value.items()}
        if isinstance(value, list):
            return [replace_assets(item) for item in value]
        if isinstance(value, str) and value.startswith("asset://"):
            return urls[value[len("asset://"):]]
        return value

    save = replace_assets(save)
    roots = save["ObjectStates"]
    decks = [obj for obj in roots if "poti_main" in obj.get("Tags", []) and obj["Name"] in ("Deck", "DeckCustom")]
    if len(decks) != 2:
        raise ValueError("Native TTS layout must contain two player decks")
    used = {obj["GUID"] for obj in roots}
    reset_decks: dict[str, str] = {}
    for color_index, color in enumerate(("blue", "red")):
        deck = next(obj for obj in decks if f"poti_{color}" in obj["Tags"])
        prototype = deck["ContainedObjects"][0]
        first_key = 101 + color_index * len(specs)
        custom = {
            str(first_key + index): {
                "FaceURL": urls[f"cards_{color}_{index + 1}.jpg"],
                "BackURL": urls["back_" + color + Path(game["backs"][color]).suffix.lower()],
                "NumWidth": columns, "NumHeight": rows, "BackIsHidden": True,
                "UniqueBack": False, "Type": 0,
            }
            for index, (columns, rows, _) in enumerate(specs)
        }
        cards = []
        for index, (card_type, card_data) in enumerate(types):
            card = copy.deepcopy(prototype)
            salt = 0
            while True:
                guid = hashlib.sha256(f"{game['id']}/{color}/{index}/{salt}".encode()).hexdigest()[:6]
                if guid not in used:
                    used.add(guid)
                    break
                salt += 1
            key = str(first_key + index // 16)
            card.update({
                "GUID": guid, "CardID": int(key) * 100 + index % 16,
                "Nickname": card_data["name"], "Description": card_data["text"],
                "Value": int(card_data["c"]), "Hands": True, "SidewaysCard": False,
                "Tags": list(deck["Tags"]), "CustomDeck": {key: copy.deepcopy(custom[key])},
                "GMNotes": json.dumps({"pcio_type": card_type, "owner": color, "trigger": card_data["s"]}, ensure_ascii=False, separators=(",", ":")),
            })
            cards.append(card)
        random.Random(12019 + color_index).shuffle(cards)
        deck.update({"ContainedObjects": cards, "DeckIDs": [card["CardID"] for card in cards],
                     "CustomDeck": custom, "Hands": True, "SidewaysCard": False})
        reset_decks[color] = json.dumps(remove_guids(deck), ensure_ascii=False, separators=(",", ":"))

    lua = lua_path.read_text(encoding="utf-8")
    asset_block = "-- BEGIN GENERATED PUBLIC ASSETS\nlocal ASSET_URLS = {\n" + "\n".join(
        f"    [{lua_string(name)}] = {lua_string(url)}," for name, url in sorted(urls.items())
    ) + "\n}\n-- END GENERATED PUBLIC ASSETS"
    lua, replacements = re.subn(r"-- BEGIN GENERATED PUBLIC ASSETS.*?-- END GENERATED PUBLIC ASSETS", lambda _: asset_block, lua, flags=re.S)
    if replacements != 1:
        raise ValueError("Lua template needs exactly one generated asset block")
    reset_block = "-- BEGIN GENERATED PLAYER DECKS\nlocal PLAYER_DECK_JSON = {\n" + "\n".join(
        f"    {color} = {lua_long_string(data)}," for color, data in reset_decks.items()
    ) + "\n}\n-- END GENERATED PLAYER DECKS\n"
    lua = lua.replace("local BUILD_TAG =", reset_block + "local BUILD_TAG =", 1)
    save["SaveName"] = f"{game['title']} {game['version']}"
    save["GameMode"] = game["title"]
    save["Note"] = "Собрано из единого эталона source/game. Правила разыгрываются вручную."
    save["LuaScript"] = lua
    # Base metadata follows canonical ids as well as their illustrations.
    for base in game["bases"]:
        obj = next(obj for obj in roots if "poti_base" in obj.get("Tags", []) and f"poti_{base['color']}" in obj["Tags"])
        obj["GMNotes"] = json.dumps({"pcio_type": base["id"], "owner": base["color"], "kind": "base"}, ensure_ascii=False)
    write_json(output / f"{game['id']}.json", save)
    (output / "tts_bootstrap.lua").write_text(lua, encoding="utf-8")
    return output / f"{game['id']}.json"
